export function parseNumber(value){if(value===null||value===undefined)return null;let s=String(value).trim().replace(/\s/g,'').replace(/[^0-9,.-]/g,'');if(!s)return null;if(s.includes(',')&&s.includes('.')){s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'')}else if(s.includes(',')){s=s.replace(',','.')}const n=Number(s);return Number.isFinite(n)?n:null}
function clean(s){return String(s??'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()}
function tableRows(html){const doc=new DOMParser().parseFromString(html,'text/html');return [...doc.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(c=>clean(c.textContent)).filter(Boolean)).filter(r=>r.length)}
function findValue(rows,labels){const wanted=labels.map(x=>x.toLowerCase());for(const row of rows){for(let i=0;i<row.length;i++){const cell=row[i].toLowerCase();if(wanted.some(w=>cell===w||cell.includes(w))){for(let j=i+1;j<row.length;j++){const n=parseNumber(row[j]);if(n!==null)return n}}}}return null}
function findText(rows,labels){const wanted=labels.map(x=>x.toLowerCase());for(const row of rows){for(let i=0;i<row.length;i++){const cell=row[i].toLowerCase();if(wanted.some(w=>cell===w||cell.includes(w)))return row[i+1]||''}}return ''}
function extractTradeRows(rows){const trades=[];for(const row of rows){if(row.length<4)continue;const joined=row.join(' ').toLowerCase();if(!/(buy|sell|balance|deal|position)/.test(joined))continue;const nums=row.map(parseNumber);const money=nums.filter(n=>n!==null);if(money.length<1)continue;const profit=money[money.length-1];if(!Number.isFinite(profit))continue;if(/balance|deposit|withdrawal/.test(joined))continue;trades.push({label:row[0],profit})}return trades}
export function parseMT5HTML(text,filename='report.html'){const rows=tableRows(text);const initial=findValue(rows,['Initial Deposit','Initial balance','Initial deposit','Balance at start']);const final=findValue(rows,['Balance','Final Balance','Total Net Profit'])!==null?findValue(rows,['Balance','Final Balance']):null;const net=findValue(rows,['Total Net Profit','Net Profit','Profit']);const grossProfit=findValue(rows,['Gross Profit']);const grossLoss=findValue(rows,['Gross Loss']);const pf=findValue(rows,['Profit Factor']);const trades=findValue(rows,['Total Trades','Trades','Deals']);const winRate=findValue(rows,['Profit Trades (% of total)','Winning Trades']);const dd=findValue(rows,['Maximal Drawdown','Maximum Drawdown','Max Drawdown']);const sharpe=findValue(rows,['Sharpe Ratio','Sharpe']);const period=findText(rows,['History Quality','Period','Dates','Tested Period']);const tradeRows=extractTradeRows(rows);return normalize({source:'MT5 HTML',filename,initial,final,net,grossProfit,grossLoss,pf,trades,winRate,dd,sharpe,period,tradeRows})}
function csvRows(text){const lines=text.replace(/\r/g,'').split('\n').filter(Boolean);return lines.map(line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out})}
export function parseMT5CSV(text,filename='report.csv'){const rows=csvRows(text);const headers=rows[0]?.map(x=>x.toLowerCase())||[];let profitIdx=headers.findIndex(x=>/profit|net profit|p&l/.test(x));let dateIdx=headers.findIndex(x=>/time|date/.test(x));const trades=[];for(const row of rows.slice(1)){if(profitIdx>=0){const p=parseNumber(row[profitIdx]);if(p!==null)trades.push({label:dateIdx>=0?row[dateIdx]:'Trade '+trades.length,profit:p})}}const profits=trades.map(t=>t.profit);return normalize({source:'MT5 CSV',filename,trades:trades.length,tradeRows:trades,net:profits.reduce((a,b)=>a+b,0),period:dateIdx>=0?`${rows[1]?.[dateIdx]||''} → ${rows.at(-1)?.[dateIdx]||''}`:''})}
export function normalize(data){const ts=data.tradeRows||[];const wins=ts.filter(t=>t.profit>0),losses=ts.filter(t=>t.profit<0);const net=data.net??ts.reduce((s,t)=>s+t.profit,0);const grossProfit=data.grossProfit??wins.reduce((s,t)=>s+t.profit,0);const grossLoss=data.grossLoss??losses.reduce((s,t)=>s+t.profit,0);const count=data.trades??ts.length;const equity=[];let running=data.initial??0;equity.push(running);for(const t of ts){running+=t.profit;equity.push(running)}return {...data,initial:data.initial??(equity[0]||0),final:data.final??running,net,grossProfit,grossLoss,pf:data.pf??(grossLoss?grossProfit/Math.abs(grossLoss):null),trades:count,winRate:data.winRate??(count?wins.length/count*100:null),tradeRows:ts,equity}}
export async function parseFile(file){const text=await file.text();if(/\.csv$/i.test(file.name)||file.type==='text/csv')return parseMT5CSV(text,file.name);return parseMT5HTML(text,file.name)}